spring.application.name=Zoop

# Configura��es do Banco de Dados
#spring.datasource.url=${JDBC_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/MultShop
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Para Hibernate 6.x + PostgreSQL 16/17 + PostGIS 3.x:
# spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPGDialect

# Configura��es do H2
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# Configura��es do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor
server.port=8080

# Evita erros de Whitelabel Error Page
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false